# Generated by Django 3.2.13 on 2022-07-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_follow_dont_follow_yourself'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
