# Generated by Django 3.2.13 on 2022-07-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('-id',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ('-id',), 'verbose_name': 'Количество интредиентов', 'verbose_name_plural': 'Количество интредиентов'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-id',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
