# Generated by Django 3.2.13 on 2022-07-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
